import Image from 'next/image';
import Header from '@/components/Header';
import Hero from '@/components/Hero';
import Gallery from '@/components/Gallery';
import BookingForm from '@/components/BookingForm';
const artists = [
  { id: 'amara', name: 'Amara Vale', specialty: 'Fine line / botanical', work: 'botanical', description: 'Amara leaves room for the skin to breathe. Her fine-line plants are drawn slowly, with as much care for the open space as the ink.', sample: 'Fine botanical linework on a forearm' },
  { id: 'eli', name: 'Eli Mercer', specialty: 'Blackwork / illustrative', work: 'moth', description: 'Eli comes from printmaking. He builds his images in dark shapes and fine cuts, so every small detail has somewhere to sit.', sample: 'A detailed blackwork moth on an upper arm' },
  { id: 'santi', name: 'Santi Reyes', specialty: 'Colour / neo-traditional', work: 'peony', description: 'Santi draws bold, familiar forms, then makes them his own with a quieter eye for colour and how it settles into skin.', sample: 'A burgundy neo-traditional peony on brown skin' },
];
export default function Home() {
  return <><Header /><main><Hero />
    <section id="studio" className="studio section-wrap">
      <div className="section-heading"><p className="section-label">The house</p><span className="mono">A good place to start.</span></div>
      <div className="studio-statement"><h2>The needle<br />can wait.</h2><div><p className="lead">First, we want to hear what brought you here.</p><p>Some people arrive with a drawing. Some bring an old photograph and a sentence they have been carrying for years. Both are a start.</p><p>We talk through the idea, the placement, and what you want the piece to hold. No rush to book. No pressure to have it all figured out.</p></div></div>
      <figure className="studio-photo"><Image src="/images/studio.webp" alt="A quiet tattoo atelier with worn timber floors, black leather chairs and afternoon light through industrial windows" fill sizes="(max-width: 767px) 100vw, 92vw" /><figcaption className="photo-note">A look around the studio.</figcaption></figure>
      <div className="studio-foot mono"><span>One client at a time</span><span>By appointment</span></div>
    </section>
    <section id="artists" className="artists section-wrap"><div className="section-heading"><p className="section-label">The artists</p><span className="mono">Three artists. Three ways of seeing.</span></div><div className="artists-intro"><h2>Different hands.<br />Different marks.</h2><p>Take a look around.<br />See whose work speaks to you.</p></div><div className="artist-layout">{artists.map(artist => <article key={artist.id} className={`artist artist-${artist.id}`}><div className="artist-portrait"><Image src={`/images/${artist.id}.webp`} alt={`${artist.name}, resident tattoo artist, photographed candidly in the studio`} fill sizes="(max-width: 600px) 80vw, (max-width: 1000px) 43vw, 30vw" /><a href="#work" className="artist-sample" aria-label={`Explore ${artist.name}'s work`}><Image src={`/images/work-${artist.work}.webp`} alt={artist.sample} fill sizes="(max-width: 600px) 28vw, 14vw" /><span>See their work</span></a></div><div className="artist-info"><p className="mono specialty">{artist.specialty}</p><h3>{artist.name}</h3><p>{artist.description}</p><a href="#book" className="text-link">Ask for {artist.name.split(' ')[0]}</a></div></article>)}</div></section>
    <section id="work" className="selected-work section-wrap"><div className="section-heading"><p className="section-label">On the skin</p><span className="mono">Recent pieces / 01—06</span></div><div className="work-intro"><h2>Made for<br />one person.</h2><p>These designs were drawn for the people wearing them. No flash sheets, no second copies.</p></div><Gallery /><p className="gallery-end mono">Open a piece to see the artist, placement, and thinking behind it.</p></section>
    <section className="appointment" id="appointment"><div className="section-wrap"><div className="section-heading"><p className="section-label">How it happens</p><span className="mono">A clear process. Room to think.</span></div><div className="appointment-layout"><h2>We start<br />with a talk.</h2><div className="steps"><article><span className="step-number mono">01</span><div><h3>Tell us the idea</h3><p>Bring a reference, a rough sketch, a place, a person, or just a few words. We can work with a beginning.</p></div></article><article><span className="step-number mono">02</span><div><h3>Draw it together</h3><p>Your artist designs for your body, not a blank page. We make changes with you until the piece feels right.</p></div></article><article><span className="step-number mono">03</span><div><h3>Make a day of it</h3><p>We set aside time for one client at a time. You leave with clear aftercare and a way to reach us while it heals.</p></div></article></div></div><div className="appointment-bottom"><span>No borrowed designs. No need to decide today.</span><a className="button button-dark" href="#book">Tell us your idea</a></div></div></section>
    <section id="visit" className="visit section-wrap"><div className="section-heading"><p className="section-label">Come by</p><span className="mono">The room, before the appointment.</span></div><div className="visit-layout"><div className="visit-image"><Image src="/images/visit.webp" alt="An open botanical sketchbook on a worn oak consultation table beside a tall studio window" fill sizes="(max-width: 767px) 92vw, 55vw" /></div><div className="visit-copy"><h2>A quiet room<br />to begin.</h2><p>Come in, have a look, ask the questions you have. You do not need to arrive with a finished idea.</p><div className="visit-details"><div><h3>Find us</h3><address>Studio address to be announced<br />Visits by appointment only</address></div><div><h3>Studio hours</h3><p>Tuesday–Saturday<br />11:00–19:00</p></div><div className="visit-email"><h3>Write to us</h3><p>booking@nocturne.example</p><span className="mono">Demo contact</span></div></div></div></div></section>
    <section id="book" className="booking section-wrap"><div className="booking-intro"><p className="section-label">Start here</p><h2>What have<br />you been<br />thinking about?</h2><p>A few lines is plenty. We’ll take it from there.</p></div><BookingForm /></section>
  </main><footer className="footer section-wrap"><div className="footer-top"><a className="wordmark" href="#top">NOCTURNE<span>TATTOO HOUSE</span></a><p>Bring the idea.<br />We’ll make room for it.</p><a className="text-link" href="#top">Back to the top</a></div><div className="footer-bottom mono"><span>© 2026 Nocturne Tattoo House</span><span>Private work. By appointment.</span><span>For the long run.</span></div></footer></>;
}
