import Image from 'next/image';
import Header from '@/components/Header';
import Hero from '@/components/Hero';
import Gallery from '@/components/Gallery';
import BookingForm from '@/components/BookingForm';
import StudioSection from '@/components/StudioSection';
import ArtistsSection from '@/components/ArtistsSection';
export default function Home() {
  return <><Header /><main><Hero />
    <StudioSection />
    <ArtistsSection />
    <section id="work" className="selected-work section-wrap"><div className="section-heading"><p className="section-label">On the skin</p><span className="mono">A small tattoo atlas / 01—06</span></div><div className="work-intro"><h2>Drawn for<br />a body.</h2><p>Every piece begins with a person, then finds the line only their body can hold. No flash sheets. No second copies.</p></div><Gallery /><p className="gallery-end mono">Open a tattoo note for its artist, placement, and the thinking behind it.</p></section>
    <section className="appointment" id="appointment"><div className="section-wrap"><div className="section-heading"><p className="section-label">How it happens</p><span className="mono">A clear process. Room to think.</span></div><div className="appointment-layout"><h2>We start<br />with a talk.</h2><div className="steps"><article><span className="step-number mono">01</span><div><h3>Tell us the idea</h3><p>Bring a reference, a rough sketch, a place, a person, or just a few words. We can work with a beginning.</p></div></article><article><span className="step-number mono">02</span><div><h3>Draw it together</h3><p>Your artist designs for your body, not a blank page. We make changes with you until the piece feels right.</p></div></article><article><span className="step-number mono">03</span><div><h3>Make a day of it</h3><p>We set aside time for one client at a time. You leave with clear aftercare and a way to reach us while it heals.</p></div></article></div></div><div className="appointment-bottom"><span>No borrowed designs. No need to decide today.</span><a className="button button-dark" href="#book">Tell us your idea</a></div></div></section>
    <section id="visit" className="visit section-wrap"><div className="section-heading"><p className="section-label">Come by</p><span className="mono">The room, before the appointment.</span></div><div className="visit-layout"><div className="visit-image"><Image src="/images/visit.webp" alt="An open botanical sketchbook on a worn oak consultation table beside a tall studio window" fill sizes="(max-width: 767px) 92vw, 55vw" /></div><div className="visit-copy"><h2>A quiet room<br />to begin.</h2><p>Come in, have a look, ask the questions you have. You do not need to arrive with a finished idea.</p><div className="visit-details"><div><h3>Find us</h3><address>Studio address to be announced<br />Visits by appointment only</address></div><div><h3>Studio hours</h3><p>Tuesday–Saturday<br />11:00–19:00</p></div><div className="visit-email"><h3>Write to us</h3><p>booking@nocturne.example</p><span className="mono">Demo contact</span></div></div></div></div></section>
    <section id="book" className="booking section-wrap"><div className="booking-intro"><p className="section-label">Start here</p><h2>What have<br />you been<br />thinking about?</h2><p>A few lines is plenty. We’ll take it from there.</p></div><BookingForm /></section>
  </main><footer className="footer section-wrap"><div className="footer-top"><a className="wordmark" href="#top">NOCTURNE<span>TATTOO HOUSE</span></a><p>Bring the idea.<br />We’ll make room for it.</p><a className="text-link" href="#top">Back to the top</a></div><div className="footer-bottom mono"><span>© 2026 Nocturne Tattoo House</span><span>Private work. By appointment.</span><span>For the long run.</span></div></footer></>;
}
